server:
  context-path: /salesorder
  port: 8081

#   spring.datasource.hikari.maximum-pool-size= 5
spring:
  datasource:
    #url: jdbc:postgresql://pg-ordr-mgmnt.cqdvpmnbb339.ap-south-1.rds.amazonaws.com:5432/jewelleryordr
    url: jdbc:postgresql://localhost:5432/jewelleryordr
    username: postgres
    password: pgadmin#123
    tomcat:
        max-active: 2
#        max-idle: 3 
#        min-idle: 3 
#        initial-size: 5
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        event:
          merge:
            entity_copy_observer: allow
    show-sql: false
    
  
logging:
  level:
    org:
      hibernate:
        type: error    
jsf:
  primefaces: 
    theme: sunny
    #theme: start
    
    
